alma-oss/php-coding-standard

.editorconfig
composer.json
easy-coding-standard.yml

This is just an initial import of rules currently defined in `lmc/jobs-meta` for both [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) and [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/) into Symfon-DI-like yml format which is used by (alpha) version 4 of [Symplify/EasyCodingStandard](https://github.com/Symplify/EasyCodingStandard) (ECS).
The plan is now to make use of `lmc/jobs-meta` for sharing codestyle rules obsolete and switch to ECS instead. As the integration is pretty straightforward, this will make reuse of the codestyle quite easy. ECS support excluding files and/or specific fixers, so it will also be easy to adjust the configuration for edgecases, but still benefit from the standard, well known and unified configuration format.
Codebases currenly …

Initial ECS setup according to current rules

---

easy-coding-standard.yml

This adds few new rules, not yet enforced by `jobs-meta` by default.
Some of them are however already being used by our PHP 7.1+ projects. And few others (the Symplify ones) enforce rules which we already agreed on (at least in Jobs), but which were not enforced by automatic codestyle check.
Ideas about some other ones (especially those which enforces rules we already use, but are not yet checked). Maybe https://github.com/Symplify/CodingStandard#types-should-not-be-referenced-via-a-fullypartially-qualified-name-but-via-a-use-statement ?
Rules description: https://github.com/Symplify/CodingStandard, https://github.com/slevomat/coding-standard, https://github.com/FriendsOfPHP/PHP-CS-Fixer

Add few more basic rules mainly for PHP 7.1

---

easy-coding-standard.yml

The resource path [is relative to current file](http://symfony.com/doc/current/service_container/import.html#importing-configuration-with-imports).
So when `vendor/bin/ecs check` is run directly from this package (I use it eg. now during its development; also when you try applying new rules to some other codebase etc.), the relative path to the PSR-2 resource file from our `easy-coding-standard.yml` is `./vendor/symplify/easy-coding-standard/config/psr2.yml`.
However when this package itself is installed as dependency of some other package, our `easy-coding-standard.yml` file is now located in `./vendor/lmc/coding-standard/easy-coding-standard.yml`, so if you will try to load `vendor/symplify/easy-coding-standard/config/psr2.yml`, it will not work, because the resource loader will try to …

Make resrouces loading work when using directly or when installed as dependency

---

composer.json

See https://github.com/j13k/yaml-lint/issues/3

Fix yaml linter not linting multiple files

---

README.md

Current ECS version no longer has the limitation mentioned here: https://github.com/Symplify/Symplify/pull/697#issuecomment-373915457

Update readme, remove no longer relevant parts

---

README.md
composer.json
easy-coding-standard.yaml

https://github.com/Symplify/EasyCodingStandard is now 4.0.0 stable, so we can remove the alpha stuff and use its new features :tada: .
Once this is merged and tested, we can release 1.0.0 and start using this :muscle: .

Update to ECS 4.0.0 stable

---

CHANGELOG.md
README.md

Release 1.0.0 🌞

---

CHANGELOG.md
composer.json
easy-coding-standard.yaml

It does not only check Exception classes do have suffix `Exception`, but also does similar checks for [more cases](https://github.com/Symplify/CodingStandard/blob/master/src/Fixer/Naming/ClassNameSuffixByParentFixer.php#L30-L41):
```php
'*Command' => 'Command',
'*Controller' => 'Controller',
'*Repository' => 'Repository',
'*Presenter' => 'Presenter',
'*Request' => 'Request',
'*Response' => 'Response',
'*EventSubscriber' => 'EventSubscriber',
'*FixerInterface' => 'Fixer',
'*Sniff' => 'Sniff',
'*Exception' => 'Exception',
'*Handler' => 'Handler',
```
But from quick check we should be already following this conventions in our codebases as well.

Replace ExceptionNameFixer with more generic ClassNameSuffixByParenFixer

---

CHANGELOG.md
easy-coding-standard.yaml
yaml-sort-checker.yml

- `PhpUnitMockFixer`: Ensure dedicated helper methods `createMock()` and `createPartialMock()` are used where possible instead of `->getMock()`.
- `PhpUnitNoExpectationAnnotationFixer`: Use `setExpectedException()` instead of `@expectedException` annotation (see https://thephp.cc/news/2016/02/questioning-phpunit-best-practices)
- `PhpUnitSetUpTearDownVisibilityFixer`: Visibility of `setUp()` and `tearDown()` method should be kept protected as defined in PHPUnit TestCase.

Add various fixers for PHPUnit tests

---

CHANGELOG.md
easy-coding-standard.yaml

Class implementing `EventSubscriberInterface` are named `...Listener` (eg. in symfony codebase), or `...Subscriber`. But usually not `...EventSubscriber`.
And I don't think we can now agree on the same suffix which will fit all (or can we?), so lets remove this check for now.
(This PR overwrites the [default settings](https://github.com/Symplify/CodingStandard/blob/master/src/Fixer/Naming/ClassNameSuffixByParentFixer.php#L37) of the fixer, and effectively removing just the check for EventSubscriber)

Do not check EventSubscriber class suffix

---

.coveralls.yml
.travis.yml
CHANGELOG.md
composer.json
easy-coding-standard.yaml
phpstan.neon
phpunit.xml.dist
src/Fixer/SpecifyArgSeparatorFixer.php
tests/Fixer/Fixtures/Correct.txt
tests/Fixer/Fixtures/Fixed.txt
tests/Fixer/Fixtures/Wrong.txt
tests/Fixer/SpecifyArgSeparatorFixerTest.php

Fixes #17 .
To be honest, this is the first Fixer I've ever written. So any suggestions especially regarding usage of php-cs-fixer internals (the tokens stuff etc.) are welcome. Also I may overlook some simpler way how to accomplish this, so I'm open for suggestions.
Cc @TomasVotruba - I would be grateful to hear some feedback on the Fixer from you as well :heart: :-)

 Add SpecifyArgSeparatorFixer to make sure http_build_query is properly used

---

CHANGELOG.md
easy-coding-standard.yaml

PHP_CodeSniffer 3.3.0 was just released, and behavior of `Generic.Commenting.DocComment.SpacingBeforeTags` sniff code [changed](https://github.com/squizlabs/PHP_CodeSniffer/pull/1990), so even with our current excludes, it doesn't allow one-line annotations (which we use):
```
class Example
{
/** @var string */
private $userId;
/** @var string[] */
private $itemIds = [];
}
```
This will with PHP_CS 3.3.0 [cause](https://travis-ci.org/lmc-eu/matej-client-php/jobs/389033616#L1237) an error "There must be exactly one blank line before the tags in a doc comment".
This PR adds this code to other excludes of DocCommentSniff we already have in order to allow  short annotations are do not considered them codestyle violation.

Fix false positives on one-line annotations with PHP_CS 3.3.0

---

easy-coding-standard.yaml

This does not affect you if you don't use [`@covers`](https://phpunit.readthedocs.io/en/7.1/annotations.html#covers) annotation on PHPUnit tests.
But if you do (and you cover multiple classes, what is common case for integration tests), you should keep it ordered alphabetically by FQCN of covered classes. The reasoning is the same as for ordered use imports: it increases readability by ordering by vendor/packages (ie. namespaces) and minimizes risk of merge conflicts.

Order covers annotation of PHPUnit tests

---

CHANGELOG.md
composer.json
easy-coding-standard.yaml

`Symplify\CodingStandard\Fixer\Naming\ClassNameSuffixByParentFixer` was deprecated since https://github.com/Symplify/Symplify/pull/957/files and it was replaced by `Symplify\CodingStandard\Sniffs\Naming\ClassNameSuffixByParentSniff`
New implementation has most of common class name suffixes defined as defaults, so it is not explicitelly needed.
Defaults are:
```php
public $defaultParentClassToSuffixMap = [
'Command',
'Controller',
'Repository',
'Presenter',
'Request',
'Response',
'EventSubscriberInterface',
'FixerInterface',
'Sniff',
'Exception',
'Handler',
];
```

Update deprecated ClassNameSuffixByParentFixer implementation

---

CHANGELOG.md
composer.json
easy-coding-standard.yaml

`Symplify\CodingStandard\Fixer\Naming\MagicMethodsNamingFixer` was deprecated in latest ECS, because php-cs-fixer 2.13 now cointains fixer doing the same (`PhpCsFixer\Fixer\Casing\MagicMethodCasingFixer`)

Replace deprecated magic method fixer

---

easy-coding-standard.yaml

This adds some new fixers, introduced in php-cs-fixer 2.12 and 2.13.
Cast shall be used, not `settype()` - what we already everywhere do.
This unifies usage of PHPUnit's assertion methods (`$this->assert...()` instead of `static::assert...()` or `self::assert...()`). 
I don't know about any LMC project which doesn't follow this rule. And if there is some, this could simply be overwritten on project-level and changed to a different call type or completely disabled.
This is the most interesting one. It removes phpdocs, which do not add any additional information on top of what is already known from method typehints and return type.
For example:
```diff
-    /**
-     * @param string $foo
-     * @return string
-     */
public function method(string $foo): string
{
return '';
}
```
However …

Add new fixers from php-cs-fixer 2.12+

---

composer.json

See https://github.com/Symplify/Symplify/blob/master/CHANGELOG.md#v500---2018-09-15 - no change, just requires Symfony `^3.4|^4.1` instead of `^3.4|^4.0`.

Bump ECS dependency

---

CHANGELOG.md
composer.json
easy-coding-standard.yaml

Bunch of new usable fixers introduced in [latest versions](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.14/CHANGELOG.md) of php-cs-fixer.
Nothing revolutionary IMO - just a fixers for long-established best practices.
Also new configuration to keep `@mixed` annotations preserved was added (which was added to php-cs-fixer by @MortalFlesh :tada: ). This is handy eg. for those using phpstan strict rules.

Add new rules from PHP-CS-Fixer 2.14 and 2.13

---

src/Fixer/SpecifyArgSeparatorFixer.php

The currently used phpstan version includes a new check for iterable types.
If a function argument is iterable, phpstan checks that value type
of its elements is specified in PHPDoc.
Example - if a function accepts array of integers as a parameter,
the corresponding PHPDoc part should change from `array` to `array<int>`.
This commit added compliant PHPDoc to functions with iterable arguments.

Fix of Travis build failure caused by the last phpstan update

---

CHANGELOG.md
composer.json
easy-coding-standard.yaml

- `VisibilityRequiredFixer` now check visibility is declared also on class constants.
- Add `Symplify\ParamReturnAndVarTagMalformsFixer` - the `@param`, `@return` and `@var` annotations should keep standard format.
- Add new fixers from PHP-CS-Fixer 2.15 and 2.16:
- `NativeFunctionTypeDeclarationCasingFixer` - native type hints for functions should use the correct case.
- `SingleTraitInsertPerStatementFixer` - each trait `use` must be done as single statement.
- `PhpUnitDedicateAssertInternalTypeFixer` - PHPUnit assertions like `assertIsArray()` should be used over `assertInternalType()` **(PHPUnit 7.5+ required)**.
- `PhpUnitMockShortWillReturnFixer` - Use of eg. `->will($this->returnValue(..))` must be replaced by its shorter equivalent such as `->willReturn(...)`.
- …

Add new rules from Symplify and PHP-CS-Fixer 2.15 & 2.16

---

CHANGELOG.md
README.md
easy-coding-standard.yaml

See https://github.com/symplify/symplify/issues/1796 .
Thus we must release new major version of the coding standard :roll_eyes: .
Also everyone would need to do this in their `easy-coding-standard.yaml`:
```diff
imports:
-    - { resource: '%vendor_dir%/lmc/coding-standard/easy-coding-standard.yaml' }
+    - { resource: 'vendor/lmc/coding-standard/easy-coding-standard.yaml' }
```

Fix regression in latest ECS causing BC break

---

CHANGELOG.md
composer.json
easy-coding-standard.yaml
phpstan.neon

See https://github.com/squizlabs/PHP_CodeSniffer/issues/2937

Disable buggy rule of array declaration fixer

---

CHANGELOG.md
composer.json
easy-coding-standard.yaml

Since version 2.0, due to renaming of psr2 sets in ECS, these are not loaded and not applied.
Also lock lock symplify/coding-standard dependency (#39).

Fix PSR-2 rules not being used

---

CHANGELOG.md
easy-coding-standard.yaml

Inspired by @spaze's [disallowed-dangerous-calls](https://github.com/spaze/phpstan-disallowed-calls/blob/master/disallowed-dangerous-calls.neon) and [disallowed-execution-calls](https://github.com/spaze/phpstan-disallowed-calls/blob/master/disallowed-execution-calls.neon).

Forbid a few other dangerous functions

---

composer.json

New symfony causes symplify/easy-coding-standard/src/Yaml/CheckerServiceParametersShifter to crash.
This is just a quick workaround for the 2.1 branch. We will se if this need some changes in the main branch.

Lock symfony/dependency-injection version to avoid fatal errors [v2.1 branch]

---

CHANGELOG.md
composer.json

This extends workaround for 2.1 branch, made in https://github.com/lmc-eu/php-coding-standard/pull/53 . In main branch, this will be resolved by upgrading to latest ECS.
For the record, this is caused by an issue in ECS: https://github.com/symplify/symplify/issues/2872, https://github.com/symplify/symplify/issues/2873

Lock symfony dependency also for <4.4.19 [v2.1 branch]

---

.github/workflows/tests.yaml
composer.json

Php-cs-fixer [already allows PHP 8](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4702) (though not all PHP 8 features are supported).
After #56 is merged, we can allow PHP 8 as well.

Allow PHP 8

---

UPGRADE-3.0.md

This is step-by-step how to upgrade codestyle config to PHP format. Ref. #56 #51 .
Real-word example of such upgrade done by this guide: https://github.com/lmc-eu/steward/pull/270/files

Add upgrade howto

---

CHANGELOG.md
ecs.php

Add new fixers from new versions of [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/) , [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/).
See changelog below. There is nothing revolutionary, probably no change of common praxis.
Fixes #52.

Add new fixers/sniffs

---

CHANGELOG.md
composer.json

Workaround for https://github.com/symplify/symplify/issues/3130 also for 2.1 branch by locking the dependency.
For main branch we have #64 , which is a more long-term solution.

Workaround for PhpUnitExpectationFixer issue [2.1 branch]

---

CHANGELOG.md
ecs.php

This is a bit different workaround for https://github.com/symplify/symplify/issues/3130 - as it seems the root issue probably won't get fixed. On PHP <8 the coding standard will degrade gracefully - everything else will work. 
This will not have an impact at all if one already run coding standard checks on PHP 8.0+ (at least on CI server). Which is a good idea anyway.
Replaces #63 .
Related issue:
```sh
In FixerFileProcessor.php line 160:
Fixing of "...Test.php" file by "PhpCsFixer\Fixer\PhpUnit\PhpUnitExpectationFixer" failed: Id must be an int, got "string". in file /(..)./vendor/friendsofphp/php-cs-fixer/src/Tokenizer/Token.php on line 60                                                                
In Token.php line 60:
Id must be an int, got "string".  
```

Use PhpUnitExpectationFixer only on PHP 8+

---

CHANGELOG.md
phpstan.neon
src/Fixer/SpecifyArgSeparatorFixer.php
tests/Fixer/Fixtures/Correct.php.inc

Obviously the `@internal` method `PhpCsFixer\Tokenizer\Analyzer\ArgumentsAnalyzer::getArgumentInfo()` [changed its behavior](https://github.com/lmc-eu/php-coding-standard/runs/2616471377?check_suite_focus=true#step:5:13), so it needs to be reimplemented on our side.

Fix SpecifyArgSeparatorFixer incompatible with php-cs-fixer 3.0

---

CHANGELOG.md
src/Fixer/SpecifyArgSeparatorFixer.php
tests/Fixer/Fixtures/Correct.php.inc
tests/Fixer/Fixtures/Fixed.php.inc
tests/Fixer/Fixtures/Wrong.php.inc

Fixes #72 .
@janbarasek Could you please try it on your codebase?
In require-dev of composer.json:
```json
"lmc/coding-standard": "dev-fix/type-error",
```

Fix: SpecifyArgSeparatorFixer type error in PHP 7.4+ 

---

CHANGELOG.md
composer.json

New ECS versions are broken for us. So lets temporarily lock the version and see what we can do for the future.
- https://github.com/symplify/symplify/pull/4065
- https://github.com/symplify/symplify/pull/4066
- https://github.com/symplify/symplify/pull/4069

Lock ECS version because of BC breaks

---

.coveralls.yml
.github/workflows/tests.yaml

The official Coveralls GH action now [supports Clover format](https://github.com/coverallsapp/coverage-reporter/pull/99) used by PHPUnit, so we can start using it.

Replace php-coveralls with official Coveralls GH action

---

README.md

The config order is longer relevant in the new ECS config format, so no need to instruct users about this.

Docs: Update readme to respect new ECS config behavior

---

composer.json
ecs-internal.php
phpstan.neon
tests/Integration/CodingStandardTest.php
tests/Integration/Fixtures/Basic.correct.php.inc
tests/Integration/Fixtures/Basic.wrong.php.inc
tests/Integration/Fixtures/NewPhpFeatures.correct.php.inc
tests/Integration/Fixtures/NewPhpFeatures.wrong.php.inc

This tests runs the configuration against provided fixture files and makes sure they are fixed to our expected code style.  
Thanks to this, we will finally have a way how to make sure the configuration works as expected and nothing breaks.
We may also add more fixtures files later.

Chore: Add basic 'integration' tests to ensure code style is being properly checked

---

composer.json
src/Sniffs/Naming/AbstractClassNameSniff.php
src/Sniffs/Naming/ClassNameSuffixByParentSniff.php
src/Sniffs/Naming/InterfaceNameSniff.php
src/Sniffs/Naming/TraitNameSniff.php

Refactor: Remove nette/utils dependency

---

README.md
composer.json
ecs-8.1.php
ecs-8.2.php
ecs-8.3.php

I tend to believe we no longer need these files with extra config for specific PHP version:
- There aren't any check in them
- Fixers which depends on some PHP version (eg. they require PHP 8.1 features) have version detection build inside them and they don't run if they detect unsupported PHP version
- In case we would need such feature to make PHP version dependent config, we can do it directly in the ecs.php file (`if (PHP_VERSION >= xxx) { ... })`
So because of the near-to-zero value and to make the configuration simpler I suggest removing these extra files.

BREAKING CHANGE: Remove ecs-8.x.php files to simplify configuration

---

ecs.php
tests/Integration/Fixtures/NewPhpFeatures.correct.php.inc
tests/Integration/Fixtures/NewPhpFeatures.wrong.php.inc

Those fixers will not be included in next release (4.0), but will be readded as part of #95 targeted to version 4.1.
This is to provide easier upgrade path for the products which would like to make more conservative two-phases upgrade (first to 4.0 mainly to change the config, then to 4.1 to fix more code issues).

Feat: Remove the most risky fixers from the next version

---

ecs.php

Out of nowhere (even though PHP_CodeSniffer was probalby not updated in new ECS release - but maybe it was, we don't know) the sniff started to add spaces in every `declare` statement.
```diff
-<?php declare(strict_types=1);
+<?php declare(strict_types = 1);
```
... which is against PER 2.

Fix: Skip part of OperatorSpacingSniff because its incorrect behavior

---

README.md
UPGRADE-4.0.md
composer.json
ecs-internal.php
ecs.php
src/Helper/SniffClassWrapper.php
tests/Integration/CodingStandardTest.php
tests/Integration/Fixtures/Basic.correct.php.inc
tests/Integration/Fixtures/Basic.wrong.php.inc
tests/Integration/Fixtures/NewPhpFeatures.correct.php.inc
tests/Integration/Fixtures/NewPhpFeatures.wrong.php.inc
tests/Integration/Fixtures/Php81.correct.php.inc
tests/Integration/Fixtures/Php81.wrong.php.inc
tests/Integration/Fixtures/Php82.correct.php.inc
tests/Integration/Fixtures/Php82.wrong.php.inc
tests/Integration/Fixtures/PhpDoc.correct.php.inc
tests/Integration/Fixtures/PhpDoc.wrong.php.inc
tests/Integration/Fixtures/PhpUnit.correct.php.inc
tests/Integration/Fixtures/PhpUnit.wrong.php.inc

This adds many fixers added to php-cs-fixer in releases from last years. See #94.
Should not be merged to main branch before version 4.0 is released, to make these fixers included in 4.1.

Add new fixers

---

composer.json
ecs.php

RequireTrailingCommaInCallSniff is redundant thanks to TrailingCommaInMultilineFixer, which [now supports](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7989) language constructs - what was its only reals difference from RequireTrailingCommaInCallSniff.

Feat: Remove RequireTrailingCommaInCallSniff

---

ecs.php
tests/Integration/Fixtures/PhpDoc.correct.php.inc
tests/Integration/Fixtures/PhpDoc.wrong.php.inc

Ref. https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8052
The check aligns multiline descriptions vertically, with no option to disable this behavior which we don't want. So I have disabled the check.
I also have to remove related example in tests. Meaning we will now no longer check for correct spacing in phpdocs :shrug: .

Fix: Disable incorrectly behaving PhpdocAlignFixer for multiline descriptions

---

composer.json

Php-cs-fixer 3.65.0 (included in ecs 12.4+) contains broken `NullableTypeDeclarationFixer,` which could lead to syntax error in code.  It also cause unit tests to fail.
See https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8330 for the bug
This should be fixed in next php-cs-fixer release (there is already a [PR with a fix](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8331)), then we can remove the version restriction.

Deps: Temporarily restrict php-cs-fixer 3.65.0 until fix for nullable decalaration is released

---

README.md
ecs-internal.php
src/Set/SetList.php

Add setlist
